project:
  type: website

website:
  title: "TLM"
  search: false
  google-analytics: "G-2Y033C89EM"
  favicon: assets/images/icons/favicon.ico
  image: assets/images/icons/radish_icon.png
  navbar:
    #logo: img/djm.png
    background: light
    collapse: false
    right:
      - href: biography.qmd
        text: BIOGRAPHY
      - href: research.qmd
        text: RESEARCH
      - href: teaching.qmd
        text: TEACHING
      - href: talks.qmd
        text: TALKS
      - href: mas.qmd
        text: MÁS
      - href: blog.qmd
        text: BLOG
  page-footer:
    border: false
    right: "© 2023, Tamara L. Mitchell"
    center: |
      <a href="https://github.com/tamaraleemitchell">
      <i class="bi bi-github"></i></a>
      <a href="https://scholar.google.com/citations?user=W1JfaXUAAAAJ&hl=en&oi=sra">
      <i class="ai ai-google-scholar"></i></a>
      <a href="https://twitter.com/spanglishtammy">
      <i class="bi bi-twitter"></i></a>
      <a href="https://orcid.org/0000-0001-9163-2393">
      <i class="ai ai-orcid"></i></a>
      <a href="mailto:tamaraleemitchell@ubc.ca">
      <i class="bi bi-envelope"></i></a>
      <a href="assets/research/CV_TamaraMitchell.pdf">
      <i class="ai ai-cv"></i></a>

format:
  html:
    theme:
      - cosmo
      - assets/djmquarto.scss
    css: assets/styles.css
    toc: true
    include-in-header: assets/header.html
crossref:
  fig-title: ""
  fig-labels: none

editor: source

execute:
  freeze: true
